from functools import partial

from ppotune.arbiters.pairwise_arbiter import (
    RemotePairwiseArbiter,
    SequentialRemotePairwiseArbiter
)


MATH_PAIRWISE_SYSTEM_PROMPT = '''You are evaluating the performance of different language models on a mathematical reasoning task. Each model is given a problem from the MATH dataset (competition mathematics) and tasked with producing a correct and well-reasoned answer. Your job is to compare the outputs and select the model that solves the problem best.

## Problem

{{
    "question": """{prompt}"""
}}

## Model completions

The following are unordered completions with solutions generated by different models. Each output is associated with a unique model identifier.

{{
    {{
        "model_identifier": "0",
        "output": """{response0}"""
    }},
    {{
        "model_identifier": "1",
        "output": """{response1}"""
    }}
}}

## Task

Select the model that produced the best solution to the math problem. Consider:
1. Correctness of the final answer (most important)
2. Mathematical rigor and validity of reasoning steps
3. Clarity and completeness of the solution

Reply with the identifier of the best model. Our evaluation will only consider the first character of your answer, so ensure your response contains only one of the identifiers and nothing else (no quotation marks, no spaces, no new lines, ...).
'''


math_arbiter = partial(
    RemotePairwiseArbiter,
    system_prompt = MATH_PAIRWISE_SYSTEM_PROMPT
)
math_arbiter.__doc__ = """
Builder for arbiter assessing models on MATH competition mathematics task.
"""

sequential_math_arbiter = partial(
    SequentialRemotePairwiseArbiter,
    system_prompt = MATH_PAIRWISE_SYSTEM_PROMPT
)
sequential_math_arbiter.__doc__ = """
Builder for arbiter assessing models on MATH task with calling internal LLM
API sequentially (check `SequentialRemotePairwiseArbiter` doc for more info).
"""
